### ISSUE TITLE
Support Context in Go 1.8

### ISSUE THREAD

**Issue by iktakahiro** [iktakahiro/fjord#3]

**Comment by bgaifullin** [comment]
Hi. I have implemented context support here:
https://github.com/bgaifullin/dbr/commit/ca88bf107d4e76c77d5d76842552b9e97d48af58

Unfortunately I do not have tests for this yet.

**Comment by iktakahiro** [comment]
@bgaifullin Thank you for your mention. May I refer to your implementation?

I will work on it soon.

**Comment by bgaifullin** [comment]
@iktakahiro, yes, you can refer it.
I have added tests today, so the work is finished.

**Comment by iktakahiro** [comment]
@bgaifullin 
I'm sorry for being late. and thanks for your suggestion.

I've released v1.0.0 and support context.
